apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-secret
  labels:
    app: backend-demo-remi
data:
  SERVER_PORT: "9080"
  WSS_SERVER_PORT: "9081"
  PREFIX_ENDPOINT: /api
  SECRET_HASH_KEY: ZGVtby1yZW1pLXNvdXJjZS1jb2Rl
  GOOGLE_API_KEY: AIzaSyDVGPPcou6miUOrdLu7ML0VCXzd4KI9pjk
  POSTGRES_USERNAME: demo-remi
  POSTGRES_HOST: postgres
  POSTGRES_DATABASE: postgres
  POSTGRES_PASSWORD: demo-remi
  POSTGRES_PORT: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-remi-backend
  labels:
    app.kubernetes.io/name: demo-remi-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-remi-backend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-remi-backend
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: demo-remi-backend
          image: registry.digitalocean.com/demo-remi/backend:v1.0.0
          imagePullPolicy: Always
          ports:
            - name: app-port
              containerPort: 9080
          envFrom:
            - configMapRef:
                name: backend-secret
          resources:
            requests:
              cpu: "0.125"
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: demo-remi-backend
  labels:
    app.kubernetes.io/name: demo-remi-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: demo-remi-backend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 9080
