apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo-remi-backend
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: api.badmem.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-remi-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo-remi-frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: badmem.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-remi-frontend
                port:
                  number: 80
